sync:
  interval_ms: 10
  overflow: 0

defaults:
  eds_pkg: cob_hardware_config
  eds_file: "cob3-9/config/Schunk_0_63.dcf"
  #pos_unit_factor: 1000000.0
  #vel_unit_factor: 1000000.0
nodes:
  - name: pg70_finger_left_joint
    id: 10
