pub_rate: 1.0 # Optional
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
  computers:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Computers
    analyzers:
      b1:
        type: diagnostic_aggregator/DiscardAnalyzer
        path: b1
        contains: 'b1'

  io:
    type: diagnostic_aggregator/AnalyzerGroup
    path: IO
    analyzers:
      joystick:
        type: diagnostic_aggregator/DiscardAnalyzer
        path: Joystick
        contains: 'joy'

  motors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Actuators
    analyzers:
      base:
        type: diagnostic_aggregator/AnalyzerGroup
        path: Base
        analyzers:
          base:
            type: diagnostic_aggregator/GenericAnalyzer
            path: drives
            startswith: 'base/driver'
          base_twist_mux:
            type: diagnostic_aggregator/GenericAnalyzer
            path: twist_mux
            contains: 'twist_mux'

  sensors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Sensors
    analyzers:
      battery:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Battery Status
        contains: 'bms'
