frequency: 30                       #nodes update frequency in hz
update_mode: polling                #switch between poll and event driven processing [polling, event]

boards:
  ifk_general:
    serial_num: 265174
    ratiometric: true
    sensors:
      voltage:
        type: analog
        index: 1
      em_stop_laser_rear:
        type: digital_in
        index: 1
