frequency: 30                       #nodes update frequency in hz
update_mode: polling                #switch between poll and event driven processing [polling, event]

boards:
  ifk_general:
    serial_num: 337035
    ratiometric: true
    sensors:
      voltage:
        type: analog
        index: 0
      current:
        type: analog
        index: 1
